V2.1.0
EBI-Metagenomics/genomes-pipeline pull request #42
Opened 2023-06-01 09:17 UTC by mberacochea

2023-06-05 08:38 UTC, Ales-ibt requested changes
The code for updating databases and tools version looks OK to me. I just was wondering, why do we have Dockerfiles for some tools if Nextflow is using the containers from quay?

2023-06-05 08:38 UTC, Ales-ibt commented on containers/gtdb-tk/Dockerfile
Not sure why do we need this Dockerfile if Nextflow is using the container from quay

2023-06-05 08:38 UTC, Ales-ibt commented on containers/interproscan/Dockerfile
Same here. Do we need the Docker file if Nextflow uses the container from quay?

2023-06-05 09:59 UTC, tgurbich commented on containers/interproscan/Dockerfile
The container nextflow uses was uploaded to quay by us and the Dockerfile is the one from which it was made so we keep them.

2023-06-06 07:51 UTC, mberacochea commented on containers/interproscan/Dockerfile
Quay is just the hosting platform, we have the images there:
```
container 'quay.io/microbiome-informatics/genomes-pipeline.gtdb-tk:v2.3.0'
```
that is the one we pushed for GTDBtk.

2023-06-06 13:56 UTC, merged